### LOGIN
POST {{base_path}}{{port}}/auth/login
Content-Type: application/json

{
  "email": "borisaxel1998@gmail.com",
  "password": "Password@1"
}

### REFISTER USER
POST {{base_path}}{{port}}/auth/register
Content-Type: application/json

{
  "email": "e.borisaxel@gmail.com",
  "password": "Password@1",
  "firstName": "Johan",
  "lastName": "Boris",
  "organizationId": ""
}

### REFISTER ADMIN
POST {{base_path}}{{port}}/auth/register/admin
Content-Type: application/json

{
  "email": "borisaxel1998@gmail.com",
  "password": "Password@1",
  "firstName": "Boris",
  "lastName": "EBANETH"
}

### REFRESH_TOKEN
POST {{base_path}}{{port}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NDI4NTE2Zi1kYzU1LTRmYzgtYTgxMy1hOTRiMDlmNTY3NGUiLCJyZWZyZXNoVG9rZW5JZCI6ImY4ZDBmYWQ1LTFlZGUtNGE1Mi1iZDgzLTg3YzhlNTMyNDY3ZiIsImlhdCI6MTc4NjUzNzI5MiwiZXhwIjoxNzg5MTI5MjkyfQ.Vm2ph5SrGbQviOOVvQK7VUnyWFJ9PXMyXwA5pO_IQ7U"
}

### LOGOUT
POST {{base_path}}{{port}}/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NDI4NTE2Zi1kYzU1LTRmYzgtYTgxMy1hOTRiMDlmNTY3NGUiLCJlbWFpbCI6ImJvcmlzYXhlbDE5OThAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwicmVmcmVzaFRva2VuSWQiOiJmOGQwZmFkNS0xZWRlLTRhNTItYmQ4My04N2M4ZTUzMjQ2N2YiLCJpYXQiOjE3ODY1MzczNjYsImV4cCI6MTc4NjUzODI2Nn0.lImxTHRTg9NU48qwJPha9zxai7A1frN7eXvdvMKlSwk