### LOGIN
POST {{base_path}}{{port}}/auth/login
Content-Type: application/json

{
  "email": "{{admin}}",
  "password": "Password@1"
}

### REFISTER USER
POST {{base_path}}{{port}}/auth/register
Content-Type: application/json

{
  "email": "e.borisaxel@gmail.com",
  "password": "Password@1",
  "firstName": "Johan",
  "lastName": "Boris",
  "organizationId": "{{orgId}}"
}

### REFISTER ADMIN
POST {{base_path}}{{port}}/auth/register/admin
Content-Type: application/json

{
  "email": "borisaxel1998@gmail.com",
  "password": "Password@1",
  "firstName": "Boris",
  "lastName": "EBANETH"
}

### REFRESH_TOKEN
POST {{base_path}}{{port}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

### LOGOUT
POST {{base_path}}{{port}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{access_token}}