### GET request to example server
POST {{base_path}}{{port}}/invoices
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "organizationId": "{{orgId}}",
  "clientName": "Client ABC",
  "clientEmail": "client@example.com",
  "clientAddress": "Douala, Cameroon",
  "clientPhone": "074032387",
  "deliveryAmount": 1500,
  "items": [
    {
      "description": "Service de facturation",
      "quantity": 1,
      "unitPrice": 50000
    },
    {
      "description": "Support technique",
      "quantity": 2,
      "unitPrice": 25000
    }
  ]
}


### GET request to example server
PATCH {{base_path}}{{port}}/invoices/{{invoiceId}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "clientName": "Client ABC UPDATED",
  "clientEmail": "client@example.com",
  "clientAddress": "Douala, Cameroon Updated",
  "clientPhone": "074032387",
  "deliveryAmount": 1500,
  "items": [
    {
      "id": "d55ea1df-fa50-4889-a3b6-c1bef541f2cc",
      "description": "Service de facturation modifié",
      "quantity": 2,
      "unitPrice": 40000
    },
    {
      "description": "Nouvel item",
      "quantity": 1,
      "unitPrice": 15000
    }
  ],
  "deleteItemIds": ["e09f346b-fc5d-4268-b1b3-22a0529c54cb"]
}


### Marquer comme payée
PATCH {{base_path}}{{port}}/invoices/paid/{{invoiceId}}
Authorization: Bearer {{access_token}}


### Annuler
PATCH {{base_path}}{{port}}/invoices/cancel/{{invoiceId}}
Authorization: Bearer {{access_token}}

### Récupérer toutes les invoices
GET {{base_path}}{{port}}/invoices
Authorization: Bearer {{access_token}}

### Avec filtres
GET {{base_path}}{{port}}/invoices?page=1&limit=20&search=FAC&status=DRAFT
Authorization: Bearer {{access_token}}

### Admin récupérant les invoices d'une org spécifique
GET {{base_path}}{{port}}/invoices?organizationId={{orgId}}
Authorization: Bearer {{access_token}}

### Récupérer une seule invoice
GET {{base_path}}{{port}}/invoices/{{invoiceId}}
Authorization: Bearer {{access_token}}