### CREATE
POST {{base_path}}{{port}}/organizations
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "SPACE",
  "email": "spacebo241@gmail.com",
  "phone": "077909090",
  "address": "CEYO"
}

### RETRIEVE
GET {{base_path}}{{port}}/organizations/6b9450e7-b55e-4ed7-b740-70fd5ed3b121
Authorization: Bearer {{access_token}}


### UPDATE
PATCH {{base_path}}{{port}}/organizations/6b9450e7-b55e-4ed7-b740-70fd5ed3b121/info
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "SPACE",
  "email": "spacebo241@gmail.com",
  "phone": "077101010",
  "address": "Chantier moderne / CEYO"
}

### STATUS
PATCH {{base_path}}{{port}}/organizations/6b9450e7-b55e-4ed7-b740-70fd5ed3b121/status
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "status": "SUSPENDED"
}

### LOGO
PATCH {{base_path}}{{port}}/organizations/6b9450e7-b55e-4ed7-b740-70fd5ed3b121/logo
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "logoUrl": "https://facturly-webapp.vercel.app/logo.png"
}

### RETRIEVE ALL
GET {{base_path}}{{port}}/organizations?search=space&page=1&limit=20
Authorization: Bearer {{access_token}}